### ISSUE TITLE
NEAR lost after deleting account with non activated beneficiary

### ISSUE THREAD

**Issue by antunmod** [near/near-api-py#22]
Hi,

I've sent NEAR and deleted my account with the **delete_account** function. The account was deleted, but the balance was not transferred to the beneficiary account. I've checked the transaction and seen an error with type **accountDoesNotExist**.

I have tried the same thing multiple times, and it only works if some NEAR was already sent to the beneficiary address. Is my only solution for this to send a small transaction before each **delete_account**, or is there a better way?

Shouldn't **delete_account** be able to transfer balance to an account that is not activated?

Account: https://explorer.near.org/accounts/eb4c47622b95401af33566b83b3719c5a93c4773fc7e7cc02285f553f82ad3e4
Transaction: https://explorer.near.org/transactions/itFhksDYPCFqRgAeLXBUVhFeW1fU5G52R8o961MRnZx

Thanks!

**Comment by frol** [comment]
According to the [NEAR Protocol rules](https://nomicon.io/DataStructures/Account#implicit-account-creation), account must exist in order to receive the remaining balance. It has nothing to do with near-api-py implementation, so I am closing this issue. The delete action was successful, and then it is clear that the transfer failed as the beneficiary account did not exist at the time of deletion:

<img width="982" alt="image" src="https://github.com/near/near-api-py/assets/304265/19c99952-4e2f-4a79-9d92-2a1f20dc3835">
